spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rbac?characterEncoding=utf-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: root

#mybatis 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

security:
  jwt:
    secretKey: whatever