server:
  port: 8980

spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      server-addr: 192.168.80.10:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swvideo?characterEncoding=UTF-8&useSSL=false
    username: root
    password: jsw
  redis:
    host: 10.15.0.3
    port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.swei.entity

logging:
  level:
    com.baizhi.dao: debug