server:
  port: 8080

spring:
  application:
    name: eureka-client-a

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-with-eureka: true # ????eureka-sever??
    fetch-refistry: true # ?????????????
    registry-fetch-interval-seconds: 10 # ?????????????
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true # ??ip
    lease-renewal-interval-in-seconds: 10  # ???????????