#server:
#  port: 8761
#
#spring:
#  application:
#    name: eureka-sever # ????
#
#euraka:
#  server:
#    eviction-interval-timer-in-ms: 10000 # ??????????????
#    renewal-percent-threshold: 0.85 # ????? ???????????????
#
#  instance:
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    hostname: localhost
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5  # ???????????

server:
  port: 8761

spring:
  application:
    name: eureka-sever # ????

euraka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka
    instance:
      instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
      hostname: localhost
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5  # ???????????