server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sw_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jsw
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间, 默认600000 (10分钟)
      idle-timeout: 180000
      # 最大连接数, 默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间, 0表示永久存活, 默认1800000 (30分钟)
      max-lifetime: 1800000
      # 连接超时时间, 默认30000 (30秒)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

  redis:
    timeout: 10000ms
    host: 192.168.80.10
    port: 6379
    database: 0 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

